export * from './cleanTemplatesList';
export * from './existFolder';
export * from './existTemplate';
export * from './formatCleanTemplate';
export * from './getBaseURL';
export * from './isValidFolderName';
export * from './isClosedByUser';
export * from './isCurrentDirectory';
export * from './getVersion';